#pragma once

#include "hardware/pio.h"
#include "hardware/gpio.h"

void nespad_program_init(PIO pio, uint sm, uint data_pin_base, uint clock_pin_base);

uint32_t nespad_state();

#define NESPAD_M1(X) (1 << ((X) << 1)) 
#define NESPAD_M2(X) (NESPAD_M1(X) << 1)

#define NESPAD_BP_B 0
#define NESPAD_BP_Y 1
#define NESPAD_BP_SELECT 2
#define NESPAD_BP_START 3
#define NESPAD_BP_UP 4
#define NESPAD_BP_DOWN 5
#define NESPAD_BP_LEFT 6
#define NESPAD_BP_RIGHT 7
#define NESPAD_BP_A 8
#define NESPAD_BP_X 9
#define NESPAD_BP_LS 10
#define NESPAD_BP_RS 11

#define NESPAD_M1_B NESPAD_M1(NESPAD_BP_B)
#define NESPAD_M1_Y NESPAD_M1(NESPAD_BP_Y)
#define NESPAD_M1_SELECT NESPAD_M1(NESPAD_BP_SELECT)
#define NESPAD_M1_START NESPAD_M1(NESPAD_BP_START)
#define NESPAD_M1_UP NESPAD_M1(NESPAD_BP_UP)
#define NESPAD_M1_DOWN NESPAD_M1(NESPAD_BP_DOWN)
#define NESPAD_M1_LEFT NESPAD_M1(NESPAD_BP_LEFT)
#define NESPAD_M1_RIGHT NESPAD_M1(NESPAD_BP_RIGHT)
#define NESPAD_M1_A NESPAD_M1(NESPAD_BP_A)
#define NESPAD_M1_X NESPAD_M1(NESPAD_BP_X)
#define NESPAD_M1_LS NESPAD_M1(NESPAD_BP_LS)
#define NESPAD_M1_RS NESPAD_M1(NESPAD_BP_RS)

#define NESPAD_M2_B NESPAD_M2(NESPAD_BP_B)
#define NESPAD_M2_Y NESPAD_M2(NESPAD_BP_Y)
#define NESPAD_M2_SELECT NESPAD_M2(NESPAD_BP_SELECT)
#define NESPAD_M2_START NESPAD_M2(NESPAD_BP_START)
#define NESPAD_M2_UP NESPAD_M2(NESPAD_BP_UP)
#define NESPAD_M2_DOWN NESPAD_M2(NESPAD_BP_DOWN)
#define NESPAD_M2_LEFT NESPAD_M2(NESPAD_BP_LEFT)
#define NESPAD_M2_RIGHT NESPAD_M2(NESPAD_BP_RIGHT)
#define NESPAD_M2_A NESPAD_M2(NESPAD_BP_A)
#define NESPAD_M2_X NESPAD_M2(NESPAD_BP_X)
#define NESPAD_M2_LS NESPAD_M2(NESPAD_BP_LS)
#define NESPAD_M2_RS NESPAD_M2(NESPAD_BP_RS)